# Generated by Django 3.2.19 on 2024-09-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, help_text='Field will be filled automatically if no value is specified.', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='named_url',
            field=models.SlugField(blank=True, help_text='Field will be filled automatically if no value is specified.', max_length=100, null=True, verbose_name='Named URL'),
        ),
    ]
